# Generated by Django 4.2.6 on 2023-10-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
    ]
